id: T-6wblsz
key: journal/today-journal-invitation/today-journal-surface
title: Render and route the Today Journal invitation
status: in_review
blocked: false
owner: jc
proposed_by: jc
depends_on:
    - T-19qcbl
accepted_against:
    spec:
        kind: git_blob
        value: git:d9db264608d07620a4f3c82884d3955f39e94b86
        path: .tiller/epics/journal/features/today-journal-invitation/tasks/today-journal-surface/task.md
        observed_at: 2026-08-19T22:51:21.364427Z
    commit:
        kind: git_commit
        value: git:e514010
        observed_at: 2026-08-19T22:51:21.387266Z
pr: 65
gates:
    build:
        required: true
        kind: command
        status: pass
        run_by: jc
        run_at: 2026-08-22T18:56:23.456351Z
        against:
            kind: git_commit
            value: git:184f100
            observed_at: 2026-08-22T18:56:23.456345Z
        evidence:
            - kind: command_output
              ref: artifacts/tiller/gates/build-184f100-out-81052b4e2eb5bd48da8bb59091743984b06c9f6cec772c1c4174b7ea05154aa9.txt
    tests:
        required: true
        kind: command
        status: pass
        run_by: jc
        run_at: 2026-08-22T18:56:23.456351Z
        against:
            kind: git_commit
            value: git:184f100
            observed_at: 2026-08-22T18:56:23.456345Z
        evidence:
            - kind: command_output
              ref: artifacts/tiller/gates/tests-184f100-out-d36b6a27ff4b09b9b77bce9c3f0ba7f3bc162941d32a476a16f7670292088561.txt
