id: T-jg4df3
key: habit-engine/log-entry-operations/entry-append-delete
title: Append and delete editable log entries
status: in_review
blocked: false
owner: jc
proposed_by: jc
accepted_against:
    spec:
        kind: git_blob
        value: git:5d06746ae730488440ac8f4b0365478dd410dc8b
        path: .tiller/epics/habit-engine/features/log-entry-operations/tasks/entry-append-delete/task.md
        observed_at: 2026-08-01T17:46:00.76591Z
    commit:
        kind: git_commit
        value: git:48e2ba2
        observed_at: 2026-08-01T17:46:00.784098Z
pr: 10
gates:
    build:
        required: true
        kind: command
        status: pass
        run_by: jc
        run_at: 2026-08-01T19:01:01.30719Z
        against:
            kind: git_commit
            value: git:4a7b4bc
            observed_at: 2026-08-01T19:01:01.307185Z
        evidence:
            - kind: command_output
              ref: artifacts/tiller/gates/build-4a7b4bc-out-a86b9ee5bee5236d1f12be1da389b1056c40a05b5b1b4af119af9dc2008dcc6d.txt
    tests:
        required: true
        kind: command
        status: pass
        run_by: jc
        run_at: 2026-08-01T19:01:01.30719Z
        against:
            kind: git_commit
            value: git:4a7b4bc
            observed_at: 2026-08-01T19:01:01.307185Z
        evidence:
            - kind: command_output
              ref: artifacts/tiller/gates/tests-4a7b4bc-out-dd069c6d93569e49bfa8666187f943e4f90997ea1648f85eda85a67943a46d9e.txt
