id: T-ozqgzt
key: goals/goal-experience/goal-form
title: Build the validated New and Edit goal form
status: check
blocked: false
owner: jc
proposed_by: jc
accepted_against:
    spec:
        kind: git_blob
        value: git:3b662fa56aef09be7504f493c6526327e762b835
        path: .tiller/epics/goals/features/goal-experience/tasks/goal-form/task.md
        observed_at: 2026-08-15T02:17:24.738343Z
    commit:
        kind: git_commit
        value: git:cf1df1a
        observed_at: 2026-08-15T02:17:24.767276Z
gates:
    build:
        required: true
        kind: command
        status: pass
        run_by: jc
        run_at: 2026-08-17T19:38:43.926196Z
        against:
            kind: sha256
            value: sha256:de7de0cd72c2717b3d20a98d7a7c591c21ea3383c7cbf4bf2cc5ededaadfdbb6
            observed_at: 2026-08-17T19:38:43.926191Z
        evidence:
            - kind: command_output
              ref: artifacts/tiller/gates/build-sha256-de7de0cd72c2-out-426883c39ccaa294fe532c63fb43fb27299e891cbaed20e8b97b2d8f95ad6ad0.txt
    tests:
        required: true
        kind: command
        status: pass
        run_by: jc
        run_at: 2026-08-17T19:38:43.926196Z
        against:
            kind: sha256
            value: sha256:de7de0cd72c2717b3d20a98d7a7c591c21ea3383c7cbf4bf2cc5ededaadfdbb6
            observed_at: 2026-08-17T19:38:43.926191Z
        evidence:
            - kind: command_output
              ref: artifacts/tiller/gates/tests-sha256-de7de0cd72c2-out-3f323f0b0e65545989298cbc7fbc1d79ab26b61b8df0ff1a565835c0d3be67a3.txt
