id: T-2tztqs
key: app-experience/fast-logging/fast-logging-model
title: Model Fast Logging Interactions
status: check
blocked: false
owner: jc
proposed_by: jc
depends_on:
    - T-qi6zgm
accepted_against:
    spec:
        kind: git_blob
        value: git:c940fdc18eb98847d053dbb5a9366ee4e6124390
        path: .tiller/epics/app-experience/features/fast-logging/tasks/fast-logging-model/task.md
        observed_at: 2026-08-05T00:46:02.634599Z
    commit:
        kind: git_commit
        value: git:51a1619
        observed_at: 2026-08-05T00:46:02.65907Z
gates:
    build:
        required: true
        kind: command
        status: pass
        run_by: jc
        run_at: 2026-08-05T16:10:22.219134Z
        against:
            kind: git_commit
            value: git:6039948
            observed_at: 2026-08-05T16:10:22.21913Z
        evidence:
            - kind: command_output
              ref: artifacts/tiller/gates/build-6039948-out-b0ce08d7cd752754ec56f3a027fb7bb843bd41753256e68fc29c13fdf76c50d4.txt
    tests:
        required: true
        kind: command
        status: pass
        run_by: jc
        run_at: 2026-08-05T16:10:22.219134Z
        against:
            kind: git_commit
            value: git:6039948
            observed_at: 2026-08-05T16:10:22.21913Z
        evidence:
            - kind: command_output
              ref: artifacts/tiller/gates/tests-6039948-out-ac33643e8a03550a3c510c34968e8f17c338069de3a56b78eab9e38b2f1b2369.txt
