id: T-g3o7wd
key: goals/today-goal-surfacing/today-goal-presentation
title: Project needful goals into Today
status: in_review
blocked: false
owner: jc
proposed_by: jc
accepted_against:
    spec:
        kind: git_blob
        value: git:8798446efc3775d4cc467c14a74740f8d394f944
        path: .tiller/epics/goals/features/today-goal-surfacing/tasks/today-goal-presentation/task.md
        observed_at: 2026-08-15T16:26:58.429539Z
    commit:
        kind: git_commit
        value: git:250c4f3
        observed_at: 2026-08-15T16:26:58.455632Z
pr: 53
gates:
    build:
        required: true
        kind: command
        status: pass
        run_by: jc
        run_at: 2026-08-18T17:42:57.493723Z
        against:
            kind: git_commit
            value: git:ec02574
            observed_at: 2026-08-18T17:42:57.493702Z
        evidence:
            - kind: command_output
              ref: artifacts/tiller/gates/build-ec02574-out-a86b9ee5bee5236d1f12be1da389b1056c40a05b5b1b4af119af9dc2008dcc6d.txt
    tests:
        required: true
        kind: command
        status: pass
        run_by: jc
        run_at: 2026-08-18T17:42:57.493723Z
        against:
            kind: git_commit
            value: git:ec02574
            observed_at: 2026-08-18T17:42:57.493702Z
        evidence:
            - kind: command_output
              ref: artifacts/tiller/gates/tests-ec02574-out-bdcb0698f824f12231285c02defde8804e2b759a9a41b93bc07546105040bf7c.txt
