id: T-96c5xx
key: habit-engine/bucket-evaluation/bucket-state-evaluation
title: Evaluate bucket state and finality
status: in_review
blocked: false
owner: jc
proposed_by: jc
depends_on:
    - T-24btkb
accepted_against:
    spec:
        kind: git_blob
        value: git:31ec0af98a17555c392eb3bcc108c3c32b36abb3
        path: .tiller/epics/habit-engine/features/bucket-evaluation/tasks/bucket-state-evaluation/task.md
        observed_at: 2026-08-01T15:32:54.797408Z
    commit:
        kind: git_commit
        value: git:a7145a5
        observed_at: 2026-08-01T15:32:54.810691Z
pr: 8
gates:
    build:
        required: true
        kind: command
        status: pass
        run_by: jc
        run_at: 2026-08-01T16:36:23.921676Z
        against:
            kind: git_commit
            value: git:106cd53
            observed_at: 2026-08-01T16:36:23.921664Z
        evidence:
            - kind: command_output
              ref: artifacts/tiller/gates/build-106cd53-out-81052b4e2eb5bd48da8bb59091743984b06c9f6cec772c1c4174b7ea05154aa9.txt
    tests:
        required: true
        kind: command
        status: pass
        run_by: jc
        run_at: 2026-08-01T16:36:23.921676Z
        against:
            kind: git_commit
            value: git:106cd53
            observed_at: 2026-08-01T16:36:23.921664Z
        evidence:
            - kind: command_output
              ref: artifacts/tiller/gates/tests-106cd53-out-c8e3fc696d4ed003cd1a5db5157feb4053655d1cb6da00f2a052b4b5c5a043da.txt
