id: T-94vmmx
key: app-experience/habit-management/first-habit-integration
title: Integrate first-habit management flows
status: in_review
blocked: false
owner: jc
proposed_by: jc
depends_on:
    - T-ogl6he
accepted_against:
    spec:
        kind: git_blob
        value: git:6e1af1db8b4707b06b559eddc6430962ced41424
        path: .tiller/epics/app-experience/features/habit-management/tasks/first-habit-integration/task.md
        observed_at: 2026-08-02T18:31:01.922725Z
    commit:
        kind: git_commit
        value: git:f38b038
        observed_at: 2026-08-02T18:31:01.939068Z
pr: 22
gates:
    build:
        required: true
        kind: command
        status: pass
        run_by: jc
        run_at: 2026-08-03T03:59:16.482549Z
        against:
            kind: sha256
            value: sha256:dd01c9a86323476a9b74f2c9249110dcb2a9a3f5b81a3588231482ac63ba12a0
            observed_at: 2026-08-03T03:59:16.482546Z
        evidence:
            - kind: command_output
              ref: artifacts/tiller/gates/build-sha256-dd01c9a86323-out-81052b4e2eb5bd48da8bb59091743984b06c9f6cec772c1c4174b7ea05154aa9.txt
    tests:
        required: true
        kind: command
        status: pass
        run_by: jc
        run_at: 2026-08-03T03:59:16.482549Z
        against:
            kind: sha256
            value: sha256:dd01c9a86323476a9b74f2c9249110dcb2a9a3f5b81a3588231482ac63ba12a0
            observed_at: 2026-08-03T03:59:16.482546Z
        evidence:
            - kind: command_output
              ref: artifacts/tiller/gates/tests-sha256-dd01c9a86323-out-29973f5c1246e27ac2a0f551ce1a638297a1bb4c9f0ac0c4b7a3920e2e721859.txt
